PACKAGE = acic_procedural
PREDICATES =

INTERFACE_FILES =		 \
	proceduralHelpers.mli    \
	proceduralClassify.mli   \
	proceduralOptimizer.mli  \
	proceduralTypes.mli      \
	proceduralMode.mli       \
	proceduralConversion.mli \
	procedural1.mli          \
	procedural2.mli          \
	proceduralTeX.mli        \
	acic2Procedural.mli      \
	$(NULL)
IMPLEMENTATION_FILES =		 \
	$(INTERFACE_FILES:%.mli=%.ml)

include ../../Makefile.defs
include ../Makefile.common
