BIN=../../

DIR=$(shell basename $$PWD)

H=@

$(DIR) all:
	$(H)$(BIN)matitac
$(DIR).opt opt all.opt:
	$(H)$(BIN)matitac.opt
clean:
	$(H)$(BIN)matitaclean
clean.opt:
	$(H)$(BIN)matitaclean.opt
depend:
	$(H)$(BIN)matitadep
depend.opt:
	$(H)$(BIN)matitadep.opt
