DIR=$(shell basename $$PWD)

$(DIR) all:
	../matitac 2>/dev/null
$(DIR).opt opt all.opt:
	../matitac.opt 2>/dev/null
clean:
	../matitaclean
clean.opt:
	../matitaclean.opt
depend:
	../matitadep
depend.opt:
	../matitadep.opt
