PACKAGE = cic_exportation
PREDICATES =

INTERFACE_FILES = \
	cicExportation.mli \
	$(NULL)
IMPLEMENTATION_FILES = $(INTERFACE_FILES:%.mli=%.ml)

# Metadata tools only need zeta-reduction
EXTRA_OBJECTS_TO_INSTALL =
EXTRA_OBJECTS_TO_CLEAN =

include ../../Makefile.defs
include ../Makefile.common
