PACKAGE = lexicon
PREDICATES =

INTERFACE_FILES =		\
	grafiteDisambiguate.mli \
	$(NULL)
IMPLEMENTATION_FILES =		\
	$(INTERFACE_FILES:%.mli=%.ml)


include ../../Makefile.defs
include ../Makefile.common
