PACKAGE = lexicon
PREDICATES =

INTERFACE_FILES =		\
	lexiconAstPp.mli		\
	lexiconMarshal.mli	\
	cicNotation.mli		\
	lexiconEngine.mli	\
	lexiconSync.mli		\
	$(NULL)
IMPLEMENTATION_FILES =		\
	lexiconAst.ml		\
	$(INTERFACE_FILES:%.mli=%.ml)


include ../../Makefile.defs
include ../Makefile.common
