PACKAGE = lexicon
PREDICATES =

INTERFACE_FILES =		\
	lexiconTypes.mli	\
	lexiconEngine.mli \
	lexiconSync.mli		\
	$(NULL)
IMPLEMENTATION_FILES =		\
	$(INTERFACE_FILES:%.mli=%.ml)


include ../../Makefile.defs
include ../Makefile.common
