PACKAGE = hgdome

# modules which have both a .ml and a .mli
INTERFACE_FILES =		\
	domMisc.mli		\
	xml2Gdome.mli		\
	$(NULL)

IMPLEMENTATION_FILES = $(INTERFACE_FILES:%.mli=%.ml)

include ../../Makefile.defs
include ../Makefile.common
