PACKAGE = cic_unification
PREDICATES =

INTERFACE_FILES = \
	cicMetaSubst.mli \
	cicMkImplicit.mli \
	termUtil.mli \
	coercGraph.mli \
	cicUnification.mli \
	cicReplace.mli \
	cicRefine.mli
IMPLEMENTATION_FILES = $(INTERFACE_FILES:%.mli=%.ml)
EXTRA_OBJECTS_TO_INSTALL =

include ../../Makefile.defs
include ../Makefile.common
