PACKAGE = cic_acic
PREDICATES =

INTERFACE_FILES =		\
	eta_fixing.mli		\
	doubleTypeInference.mli \
	cic2acic.mli		\
	cic2Xml.mli		\
	$(NULL)
IMPLEMENTATION_FILES = $(INTERFACE_FILES:%.mli=%.ml)

include ../../Makefile.defs
include ../Makefile.common
